# Generated by Django 4.0.3 on 2022-05-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0003_rename_image_project_image_cover_project_image10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='left_or_right',
            new_name='on_if_left',
        ),
    ]
