# Generated by Django 4.0.3 on 2022-05-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0005_alter_project_image10_alter_project_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image10',
            field=models.ImageField(blank=True, upload_to='my_projects/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, upload_to='my_projects/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, upload_to='my_projects/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image4',
            field=models.ImageField(blank=True, upload_to='my_projects/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image5',
            field=models.ImageField(blank=True, upload_to='my_projects/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image6',
            field=models.ImageField(blank=True, upload_to='my_projects/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image7',
            field=models.ImageField(blank=True, upload_to='my_projects/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image8',
            field=models.ImageField(blank=True, upload_to='my_projects/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image9',
            field=models.ImageField(blank=True, upload_to='my_projects/images/%Y/%m/%d/%H/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_cover',
            field=models.ImageField(upload_to='my_projects/images/%Y/%m/%d/%H/'),
        ),
    ]
