# Generated by Django 4.0.3 on 2022-05-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0006_alter_project_image10_alter_project_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='my_projects.project')),
            ],
            bases=('my_projects.project',),
        ),
    ]
